### ISSUE TITLE
Comparison with sbt-taglist

### ISSUE THREAD

**Issue by laughedelic** [fedragon/sbt-todolist#5]
Do you know about the [sbt-taglist](https://github.com/johanandren/sbt-taglist) plugin?
If yes, it would be nice to add to the readme some justification of existence of the second plugin with similar functionality.

**Comment by fedragon** [comment]
Hi @laughedelic,
this project started as (and still is) a personal exploration into sbt internals for which I needed to give myself a simple goal and finding `todo` in sources sounded simple enough.

I don't think a project should need to have a _justification of existence_ but I will write it anyway.

**Comment by laughedelic** [comment]
Thanks for reply. I just encountered this plugin in the list of community plugins in the sbt documentation and it wasn't obvious from the readme, what is the difference with the other plugin, which I knew from before.
